// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.ML;
using PokerAppML.Model;

namespace PokerAppML.Model
{
    public class ConsumeModel
    {
        private PredictionEngine<ModelInput, ModelOutput> _predictionEngine;//= new Lazy<PredictionEngine<ModelInput, ModelOutput>>(CreatePredictionEngine);


        public ConsumeModel()
        {
           _predictionEngine = CreatePredictionEngine();
        }
        // For more info on consuming ML.NET models, visit https://aka.ms/mlnet-consume
        // Method for consuming model in your app
        public  ModelOutput Predict(ModelInput input)
        {
            ModelOutput result = _predictionEngine.Predict(input);
            return result;
        }

        public static PredictionEngine<ModelInput, ModelOutput> CreatePredictionEngine()
        {
            // Create new MLContext
            MLContext mlContext = new MLContext();

            // Load model & create prediction engine

          
            string modelPath = "MLModel.zip";
            ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

            return predEngine;
        }
    }
}
